services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks: 
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks: 
      - inception
    restart: always

  # wordpress:
  #   container_name: wordpress
  #   ports:
  #     - 9000:9000
  #   environment:
  #     WORDPRESS_DB_HOST: 
  #     WORDPRESS_DB_USER: 
  #     WORDPRESS_DB_PASSWORD: 
  #     WORDPRESS_DB_NAME: 
    # depends_on:
    #   - db
    # volumes:
    #   - "./:/var/www/html"

networks:
  inception:
    driver: bridge
