services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks: 
      - inception
    restart: always
    volumes:
      - "wordpress_data:/var/www/html"
    depends_on:
      - mariadb
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks: 
      - inception
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - "mariadb_data:/var/www/html"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mariadb
    volumes:
      - "wordpress_data:/var/www/html"

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/html/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/html/db

networks:
  inception:
    driver: bridge
