services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks: 
      - inception
    restart: always
    volumes:
      - "wordpress_data:/var/www/html"
    depends_on:
      mariadb:
        condition: service_started
      wordpress:
        condition: service_started

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    networks: 
      - inception
    restart: always
    environment:
      DB_HOST: ${WP_HOST}
      DB_USER: ${WP_USER}
      DB_PASSWORD: ${WP_PASSWORD}
      DB_NAME: ${WP_NAME}
    volumes:
      - "mariadb_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 5s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    volumes:
      - "wordpress_data:/var/www/html"
    environment:
      DB_HOST: ${WP_HOST}
      DB_USER: ${WP_USER}
      DB_PASSWORD: ${WP_PASSWORD}
      DB_NAME: ${WP_NAME}

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/html/db
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/html/wordpress